In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/drive/MyDrive/titanic/Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
fare = df["Fare"]
fare.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [ ]:
age = df[["Pclass","Age"]]
age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [ ]:
survived = df[["Sex","Survived"]]
survived.head()

      Sex  Survived
0    male         0
1  female         1
2  female         1
3  female         1
4    male         0

In [ ]:
fare_gt_100 = df.loc[df["Fare"]>100]
fare_gt_100

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [ ]:
first_class = df.loc[df["Pclass"]==1]
first_class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
female_under_18 = df[(df["Age"]>18)&(df["Sex"]=='female')]
female_under_18

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [ ]:
embarked_c_or_s = df[(df["Embarked"].isin(["C","S"]))]
embarked_c_or_s

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
first_second_class = df[(df["Pclass"].isin([1,2]))]
first_second_class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

##3.2

In [8]:
missing_value = df["Age"].fillna(df["Age"].median())
missing_value

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [29]:
df["fare_per_year"] = df["Fare"]/df["Age"]
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Columns: 628 entries, PassengerId to fare_per_year
dtypes: float64(618), int64(5), object(5)
memory usage: 4.3+ MB

In [31]:
high_fare_age = df.loc[df["fare_per_year"]>5]
high_fare_age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.669643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.212500
824,825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,19.843750
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,37.004200
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,22.590361
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,7.818750

In [33]:
high_fare_age_srt = df.loc[df["fare_per_year"]>5].sort_values(by = ["fare_per_year"],ascending = False)
high_fare_age_srt

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,39.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.318281
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.300000
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.231250
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.212500
480,481,0,3,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,46.9000,...,0.857143,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,5.211111

In [35]:
result = high_fare_age_srt[["Name","fare_per_year"]]
result

                                       Name  fare_per_year
305          Allison, Master. Hudson Trevor     164.728261
297            Allison, Miss. Helen Loraine      75.775000
386         Goodwin, Master. Sidney Leonard      46.900000
164            Panula, Master. Eino Viljami      39.687500
183               Becker, Master. Richard F      39.000000
..                                      ...            ...
318                Wick, Miss. Mary Natalie       5.318281
348  Coutts, Master. William Loch "William"       5.300000
205              Strom, Miss. Telma Matilda       5.231250
813      Andersson, Miss. Ebba Iris Alfrida       5.212500
480          Goodwin, Master. Harold Victor       5.211111

[68 rows x 2 columns]

In [38]:
df["fare_per_class"]= df["Fare"]/df["Pclass"]
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year,fare_per_class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.329545,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,1.875876,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.304808,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,1.517143,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.230000,2.683333

In [40]:
adult_males = df.loc[(df["Sex"]=="male")&(df["Age"]>18)]
adult_males

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year,fare_per_class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.329545,2.416667
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.230000,2.683333
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.960417,51.862500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.402500,2.683333
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.801923,10.425000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.375000,5.250000
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.282000,2.350000
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.481481,6.500000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,1.153846,30.000000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.242188,2.583333

In [42]:
adult_male_srt = adult_males.sort_values(by = ["fare_per_class"],ascending = False)
adult_male_srt

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year,fare_per_class
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,14.231367,512.3292
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,14.637977,512.3292
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,13.842105,263.0000
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,4.109375,263.0000
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,10.313367,247.5208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.000000,0.0000
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.000000,0.0000
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.000000,0.0000
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.000000,0.0000
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.000000,0.0000

In [44]:
result = adult_male_srt[["Name","Age","fare_per_class"]]
result

                                   Name   Age  fare_per_class
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
737              Lesurer, Mr. Gustave J  35.0        512.3292
27       Fortune, Mr. Charles Alexander  19.0        263.0000
438                   Fortune, Mr. Mark  64.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208
..                                  ...   ...             ...
263               Harrison, Mr. William  40.0          0.0000
271        Tornquist, Mr. William Henry  25.0          0.0000
822     Reuchlin, Jonkheer. John George  38.0          0.0000
302     Johnson, Mr. William Cahoone Jr  19.0          0.0000
806              Andrews, Mr. Thomas Jr  39.0          0.0000

[382 rows x 3 columns]

##3.3

In [46]:
total_fare = df["Fare"].sum()
total_fare

28693.9493

In [49]:
pclass_1_fare = df.loc[df["Pclass"]==1]["Fare"].sum()
pclass_1_fare

18177.4125

In [50]:
pclass_2_fare = df.loc[df["Pclass"]==2]["Fare"].sum()
pclass_2_fare

3801.8417

In [51]:
pclass_3_fare = df.loc[df["Pclass"]==3]["Fare"].sum()
pclass_3_fare

6714.6951

In [52]:
fare_total = df.groupby("Pclass")["Fare"].sum()
fare_total

Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64

In [53]:
fare_total_list = fare_total.tolist()
fare_total_list

[18177.4125, 3801.8417, 6714.6951]

In [55]:
fare_proportion = fare_total/total_fare
fare_proportion

Pclass
1    0.633493
2    0.132496
3    0.234011
Name: Fare, dtype: float64

## What percent of the total number of passengers on the Titanic belonged to each age group
 (e.g., child, adult, senior)?

In [56]:
def checkAge(age):
    if(age<18):
        return 'child'
    elif(age>=18 and age<=64):
        return 'adult'
    else:
        return 'senior'


df['age_group'] = df['Age'].apply(checkAge)

<ipython-input-56-bcadf70289b4>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['age_group'] = df['Age'].apply(checkAge)

In [58]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year,fare_per_class,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.329545,2.416667,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,1.875876,71.283300,adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.304808,2.641667,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,1.517143,53.100000,adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.230000,2.683333,adult
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,NaN,2.819433,senior
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.960417,51.862500,adult
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,10.537500,7.025000,child
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,0.412344,3.711100,adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,...,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,2.147914,15.035400,child

In [61]:
total_passanger = df["PassengerId"].count()
total_passanger

891

In [62]:
passenger_group_sum = df.groupby("age_group").count()
passenger_group_sum

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,0.481667,0.49229,1.48497,0.478032,0.746795,1.578947,1.153846,0.242188,fare_per_year,fare_per_class
age_group,,,,,,,,,,,,,,,,,,,,,
adult,590,590,590,590,590,590,590,590,590,590,...,590,590,590,590,590,590,590,590,590,590
child,113,113,113,113,113,113,113,113,113,113,...,113,113,113,113,113,113,113,113,113,113
senior,188,188,188,188,188,11,188,188,188,188,...,188,188,188,188,188,188,188,188,11,188

In [64]:
passenger_group_sum_2 = df['age_group'].value_counts()
passenger_group_sum_2

age_group
adult     590
senior    188
child     113
Name: count, dtype: int64

In [65]:
proportion_of_passenger = passenger_group_sum_2/total_passanger
proportion_of_passenger

age_group
adult     0.662177
senior    0.210999
child     0.126824
Name: count, dtype: float64